name: Cypress test exercise 

on:
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup env
        run: echo '${{ secrets.CYPRESS_ENV }}' > cypress.env.json

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          start: npx cypress run --spec cypress/e2e/contactList/contactList.feature
